package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CategoriaProductoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaProductoAllPropertiesEquals(CategoriaProducto expected, CategoriaProducto actual) {
        assertCategoriaProductoAutoGeneratedPropertiesEquals(expected, actual);
        assertCategoriaProductoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaProductoAllUpdatablePropertiesEquals(CategoriaProducto expected, CategoriaProducto actual) {
        assertCategoriaProductoUpdatableFieldsEquals(expected, actual);
        assertCategoriaProductoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaProductoAutoGeneratedPropertiesEquals(CategoriaProducto expected, CategoriaProducto actual) {
        assertThat(expected)
            .as("Verify CategoriaProducto auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaProductoUpdatableFieldsEquals(CategoriaProducto expected, CategoriaProducto actual) {
        assertThat(expected)
            .as("Verify CategoriaProducto relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getEstablecimientoId()).as("check establecimientoId").isEqualTo(actual.getEstablecimientoId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaProductoUpdatableRelationshipsEquals(CategoriaProducto expected, CategoriaProducto actual) {
        // empty method
    }
}
